### ISSUE TITLE
기존 서비스 분석

### ISSUE THREAD

**Issue by kowoohyuk** [woowa-techcamp-2021/store-5#1]
배민문방구 사이트를 분석하며, 요구사항을 정리합니다.

**Comment by peanut-lover** [comment]
아래 사이트에서 여러 요소들을 벤치마킹해서 요구사항을 정리해보았습니다. 

[요구사항 정리 wiki](https://github.com/woowa-techcamp-2021/store-5/wiki/%EA%B8%B0%EC%A1%B4-%EC%82%AC%EC%9D%B4%ED%8A%B8%EB%B6%84%EC%84%9D-%EB%B0%8F-%EC%9A%94%EA%B5%AC%EC%82%AC%ED%95%AD-%EC%A0%95%EB%A6%AC)

- 배민문방구 사이트 [링크](https://store.baemin.com/)
- 배민상회 [링크](https://mart.baemin.com/)


추가로 백오피스(관리자 페이지), 사용자 페이지 와이어프레임 작업을 진행하기 위해 figma 작업을 같이 진행했습니다.

- [figma 작업] (https://www.figma.com/file/U9AfAHsn69Yh7hyKYCF3Xa/%EC%9A%B0%EC%95%84%ED%95%9C-%EB%AC%B8%EB%B0%A9%EA%B5%AC?node-id=0%3A1)
