### ISSUE TITLE
[FE] Recoil을 사용해 주문/결제 페이지로 상품을 전달하기

### ISSUE THREAD

**Issue by ondal1997** [woowa-techcamp-2021/store-5#103]
## :hammer: 기능 설명

Recoil을 사용해 주문/결제 페이지로 상품을 전달하기

## 📑 체크리스트

> 수행해야 할 체크리스트

- [x] Recoil을 사용해 주문/결제 페이지로 상품을 전달하기
- [x] 주문/결제 페이지 동작 개선

**Comment by peanut-lover** [comment]
리코일 시작단계에서 한번 알려주세요. 기석님을 끼고 해야 더 좋은 코드가 나올것같습니다.
