### ISSUE TITLE
기본적인 기능이 완성되가는 시점에 해야할 작업들

### ISSUE THREAD

**Issue by peanut-lover** [woowa-techcamp-2021/store-5#133]
## :hammer: 기능 설명

프로젝트 기간의 2/3가 지나가고 있는 시점에 저희 프로젝트 진행이 원활해서 추가적인 기능 혹은 디자인에 대한 내용을 이야기하고자 해당 이슈를 생성했습니다. 좋은 아이디어나 개선점들을 코멘트로 추가해서 알려주시면 감사하겠습니다. 자세히 알려주실 수록 더 도움 될 것 같습니다.

개인적으로 생각하고 있는 작업 후보들이 있습니다. 

- Client App UI/UX 개선 (자세하게  이슈로 등록해서 처리해나가야할 듯합니다.)
- Admin (BackOffice) App 기능적 개선 (사용자 관리 페이지 등등)
- Client App 어플리케이션 반응성 및 테마 개선
- Backend 코드 퀄리티를 위해 리팩토링 진행
- ~~SSR 도전! (난이도 상)~~
- 클라이언트 사이드에서 form 검증
- 백엔드 API 에서 데이터 검증
- 클라이언트 api에서 예외처리

**Comment by ondal1997** [comment]
오늘 회의 때도 말했지만, 리스트해주신 부분들 모두 다 정말 중요하다고 생각하는 부분이라고 생각합니다. 파이팅해봅니다.

**Comment by peanut-lover** [comment]
이 내용은 issue가 아니라  Discussion에서 이어가도록 합시다.!
