### ISSUE TITLE
4팀 코드리뷰

### ISSUE THREAD

**Issue by Choi-Jinwoo** [woowa-techcamp-2021/store-5#136]
4팀 코드리뷰

**Comment by momongss** [comment]
- #107 
  https://github.com/woowa-techcamp-2021/store-5/pull/107/files#r692668016

**Comment by Choi-Jinwoo** [comment]
[#98](https://github.com/woowa-techcamp-2021/store-5/pull/98/files#r692664748)
[#72] (https://github.com/woowa-techcamp-2021/store-5/pull/82/files#r692666964)
[#82] (https://github.com/woowa-techcamp-2021/store-5/pull/82/files#r692668891)
[#82] (https://github.com/woowa-techcamp-2021/store-5/pull/82/files#r692671338)
[#82] (https://github.com/woowa-techcamp-2021/store-5/pull/82/files#r692673771)

**Comment by sanginchun** [comment]
#135

**Comment by juyoungpark718** [comment]
#134
