### ISSUE TITLE
[Bug] 주문/결제 페이지 state 경고 발생

### ISSUE THREAD

**Issue by ondal1997** [woowa-techcamp-2021/store-5#137]
## ⚠️ 버그 설명

![image](https://user-images.githubusercontent.com/64543699/130193573-9d75428b-2808-4dd5-9eb0-33063a94ecbd.png)

렌더링 프로세스 중에 스테이트가 변환되는 것으로 식별됩니다.

**Comment by peanut-lover** [comment]
페이지 전화 후 컴포넌트 상태가 수정이 되네요.
