### ISSUE TITLE
[Bug] 상품 목록 조회에서 limit보다 상품이 적게 나오는 문제

### ISSUE THREAD

**Issue by kowoohyuk** [woowa-techcamp-2021/store-5#167]
현재 찜하기 목록에서 발견

ex) 페이지당 상품 수가 1이고, 마지막 페이지가 8일 때, 마지막 페이지에서 offset이 7이 아닌 6이 되는 경우

ex) limit이 4인데 상품이 3개가 조회되는 문제 (상품은 4개가 나올 수 있을 만큼 여분이 있음)

간헐적으로 발생하기에 명확한 이유 확인이 필요합니다!  
혹시 다른 분들도 비슷한 이슈가 발생한다면

<code>요청 URL</code>, <code>쿼리</code>

를 제보해주시면 감사하겠습니다! :)

**Comment by kowoohyuk** [comment]
1. 페이지가 범위를 초과하는 경우 : 정상적으로 마지막 페이지의 상품들이 출력됩니다.
> 상품수 9, page 2, limit 5 => 4개 출력 (마지막 페이지는 2페이지이므로 잔여 수량 4개)
2. 상품 수량과 페이지가 정확히 일치하는 경우 : 정상적으로 마지막 페이지의 상품들이 출력됩니다.
> 상품수 9, page 1, limit 9 => 9개 출력
3. 페이지가 0인 경우 : 정상적으로 첫 페이지의 상품들이 출력됩니다.
> 상품수 3, page 0, limit 2 => 2개 출력
4. limit이 총 상품수 보다 많은 경우 : 정상적으로 출력됩니다.
> 상품수 4, page 1, limit 200 => 4개 출력

**Comment by peanut-lover** [comment]
다시 확인해보니 데이터 이상으로 발생한 문제였습니다. 마이그레이션 반영전 데이터 무결성문제.
