### ISSUE TITLE
[Bug] Admin 페이지에서 상품 수정시 Thumbnail 이미지가 제대로 수정이 안되는 현상

### ISSUE THREAD

**Issue by peanut-lover** [woowa-techcamp-2021/store-5#196]
## :hammer: 기능 설명

<img width="218" alt="스크린샷 2021-08-24 오후 11 54 29" src="https://user-images.githubusercontent.com/20085849/130639486-a29a576b-95c1-4c08-b4aa-ed3800720b5f.png">

상품 수정 모달의 수정이 필요해보입니다.!😇

**Comment by peanut-lover** [comment]
추가로 모달을 통해 데이터를 변경했으면 다시 API 패칭을 하도록 수정하기

**Comment by peanut-lover** [comment]
@kowoohyuk  님 작업하신 부분인데 한번 확인가능할가요??

**Comment by kowoohyuk** [comment]
수정하였습니다~! 아침 PR에 이슈 링크 포함하도록 할게요!

**Comment by kowoohyuk** [comment]
이미지가 제대로 수정이 안되던 이유는 아래와 같습니다!

썸네일 이미지 자체는 상품에서 url 값으로 관리하고 있습니다.  
기존 이미지가 존재하는 상태에서 새로운 이미지를 추가했을 때, 기존 이미지의 변경을 확인하기 위해 <code>oldImages</code>라는 배열을 통해 기존의 이미지의 id값을 배열로 전달하여 썸네일 이미지를 갱신하게 되는데 이 과정에서 oldImages의 맨 앞에 있는 이미지를 썸네일 이미지로 처리하게 됩니다.

oldImages가 url이 아닌 id임을 간과하여 썸네일을 아이디로 덮어씌우는 문제였습니다 :)
