### ISSUE TITLE
우편번호가 한글로도 입력이 되네요

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/store-5#253]
## ⚠️ 버그 설명

버그 설명
<img width="552" alt="스크린샷 2021-08-27 오후 2 18 35" src="https://user-images.githubusercontent.com/75124422/131075844-ec70a184-0bd1-4684-aee0-6c1829ee2bb7.png">

우편번호 데이터 검증이 안되어 있는 것 같습니다. 글자수 제한만 뜨네요.

**Comment by peanut-lover** [comment]
@ondal1997  어진님 이거 수정이되었나요?
