### ISSUE TITLE
[FE] Custom Zoom In Module 구현하기 

### ISSUE THREAD

**Issue by peanut-lover** [woowa-techcamp-2021/store-5#35]
## :hammer: 기능 설명

상품 이미지를 Zoom 확대해서 볼 수 있도록 하는 기능 구현을 위해서  `lib`에 `CustomZoom.ts` 를 만들면 좋을 것 같습니다.

## 📑 체크리스트

> 수행해야 할 체크리스트

- [ ] 줌모듈에 필요한 옵션들을 외부에서 설정할 수 있는가?
- [ ] 줌 모듈의 성능 줌는 없는가?
- [ ] 줌 모듈을 감싸는 React Component에 성능 문제는 없는가?

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항

- 주의 사항 1
- 주의 사항 2

**Comment by peanut-lover** [comment]
@kowoohyuk  

줌모듈을 완성했다면 이슈를 닫아도 될까요? 아니면 아직 개선할 점이 있을까요

**Comment by kowoohyuk** [comment]
바로 닫아버리겠습니다! :)
