### ISSUE TITLE
[FE] 상세 페이지 테스트 코드 작성하기

### ISSUE THREAD

**Issue by kowoohyuk** [woowa-techcamp-2021/store-5#46]
## :hammer: 기능 설명

상세 페이지 테스트 코드를 작성할 예정입니다.

## 📑 체크리스트

> 수행해야 할 체크리스트

- [x] 작성한 테스트 코드가 제대로 동작하나요?

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항

- 완벽하게 작성하려고 하지 않기

## 예상 소요 시간 : 0.5D

**Comment by peanut-lover** [comment]
상세 페이지의 테스트 코드는 추가 변경이 거의 없을 예정이고 이미 직접 테스트를 통과해서 해당 부분의 렌더링 테스트는 없어도 될 듯합니다.

**Comment by kowoohyuk** [comment]
확인했습니다...  
좋은 의견이네요!

불필요한 작업은 제외하죠!!
