### ISSUE TITLE
6팀의 리뷰 ㅎㅎ

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/store-5#51]
- 황윤서
    - [[feature/18] User 엔티티 수정 #39](https://github.com/woowa-techcamp-2021/store-5/pull/39#discussion_r688268680)
    - [[feature/8] [FE] 옵저버를 활용한 동적 헤더,Login Modal [BE] github OAuth2.0 적용 #41](https://github.com/woowa-techcamp-2021/store-5/pull/41#pullrequestreview-729297437)

**Comment by qudgus21** [comment]
* 황병현
 - [typeorm 관련](https://github.com/woowa-techcamp-2021/store-5/pull/19/commits/26c756f89a7112ca4a70cdcd852e394a6fcdf16e#r688274240)
 - [typeorm 관련2](https://github.com/woowa-techcamp-2021/store-5/pull/19/commits/26c756f89a7112ca4a70cdcd852e394a6fcdf16e#r688273816)

**Comment by peanut-lover** [comment]
피드백 감사합니다. 💪 타입ORM 시작단계인데 도움이 많이 될 것 같습니다. :)
