### ISSUE TITLE
DOM 태그 개선 제안

### ISSUE THREAD

**Issue by jonghopark95** [woowa-techcamp-2021/store-5#52]
### 레이아웃 태그 개선

<img width="487" alt="스크린샷 2021-08-13 오후 3 37 04" src="https://user-images.githubusercontent.com/19240202/129315209-1b4ccbe6-0e9a-44e7-abc2-607dcaa6d48a.png">

### Navigation Bar 태그 개선

<img width="710" alt="스크린샷 2021-08-13 오후 3 42 52" src="https://user-images.githubusercontent.com/19240202/129315768-6cfe2b0f-ce52-4634-a2ef-8819a8d1b00a.png">

## 📑 체크리스트

> 해결해야하는 버그 체크리스트

- [ ] header를 제외한 모든 태그가 div로 보여지는데 아쉽다고 생각합니다.
  - [ ] main, footer, nav, aside, section 태그를 사용했으면 어땠을까 라고 생각합니다 :)
  - [ ] Navigation bar가 전부 div태그로 감싸져 있네요 ㅜ ㅜ nav, ul, li 태그를 잘 활용하는 것도 좋아 보입니다 😁

## 🚧 주의 사항

> 버그를 해결할 때 유의깊게 살펴볼 사항

- X

**Comment by peanut-lover** [comment]
sematic 태그를 적극적으로 사용해야겠네요 :)
