### ISSUE TITLE
메인 페이지 그리드 cursor: pointer 로서의 수정 제안

### ISSUE THREAD

**Issue by jonghopark95** [woowa-techcamp-2021/store-5#54]
### 메인 페이지 상품 그리드의 cursor 가 default 임

https://user-images.githubusercontent.com/19240202/129316157-ac31cf3b-2272-4852-887c-c8fe4e7c3b22.mov

## 📑 체크리스트

> 해결해야하는 버그 체크리스트

- [ ] 사소하지만, cursor: pointer를 추가하면 더 좋은 UX를 가져올 것으로 생각됩니다.

## 🚧 주의 사항

> 버그를 해결할 때 유의깊게 살펴볼 사항

- X

**Comment by peanut-lover** [comment]
오 맞습니다. ㅋㅋㅋ 바로 수정할 수 있을듯한 개선점이네요 감사합니다.
