### ISSUE TITLE
Navigation Bar, root tag에 min-height, min-width 추가 제안

### ISSUE THREAD

**Issue by jonghopark95** [woowa-techcamp-2021/store-5#55]
### Navigation Bar

https://user-images.githubusercontent.com/19240202/129317032-c9d46ec7-d4e3-4a7d-be2f-ea17cad1cf57.mov

### root

https://user-images.githubusercontent.com/19240202/129317129-2dba8c41-cf1f-4455-8767-490b9cad8253.mov

## 📑 체크리스트

> 해결해야하는 버그 체크리스트

- [ ] Navigation bar의 최소 height이 없어 로고가 튀어나오는 것 같습니다. 좋지 못한 UX로 생각됩니다.
- [ ] 화면 너비를 줄이게 될 경우 옆의 장바구니 슬라이드 위에 NEW, SALE, GREEN, BEST 태그가 위로 올라오게 됩니다. 반응형 구현을 안하신다면 최소 너비를 지정해주는 것도 좋아보입니다.

## 🚧 주의 사항

> 버그를 해결할 때 유의깊게 살펴볼 사항

- X

**Comment by peanut-lover** [comment]
감사합니다. 좋은 UI/UX 피드백인 것 같네요 😄
