### ISSUE TITLE
[BE] 제품 조회 API 구현하기

### ISSUE THREAD

**Issue by peanut-lover** [woowa-techcamp-2021/store-5#64]
## :hammer: 기능 설명

아마 아직 까지 저희가 놓치는 부분들이 있다고 생각합니다. 구현 중 문제가 발견되면 이슈에 추가로 남겨주시고 공유해주시면 감사하겠습니다.

`GET /goods/[id]` api가 구현이 완료되면 이어서 진행하면 될 것 같습니다. 

@kowoohyuk  

- 다른 사람들이 이어서 작업할 수 있게 `GET /goods/category?category="[카테고리]"&flag=best&page=1&limit=10` 를 우선적으로 만들어주세요.
- `GET /goods/keyword?keyword=""&page=0&limit=10` 는 다음으로 만들어 주시면 좋을 것 같습니다.

## 📑 체크리스트

> 수행해야 할 체크리스트

- [ ] Edge case를 다 해결할 수 있는지 확인 꼭하기
- [ ] 페이지 네이션을 할 때 어떤식으로 api를 보내면 좋을지 팀원들에게 알려주기
- [ ] API 구현이 완료되면 문서화 다시해서 wiki에 깔끔하게 작성해주세요.

**Comment by kowoohyuk** [comment]
작업 시작합니다 :)

**Comment by peanut-lover** [comment]
@kowoohyuk  이 작업은 끝났으면 이슈 닫을까요??
