### ISSUE TITLE
[FE] mainPage Section & Promotion

### ISSUE THREAD

**Issue by Kwongiseok** [woowa-techcamp-2021/store-5#9]
## :hammer: 기능 설명

기능 설명

<선택> 이해를 돕기 위한 스크린샷을 첨부해주세요.

## 📑 체크리스트

> 수행해야 할 체크리스트

- [x] Product 컴포넌트
- [x] Promotion (carousel)
- [x] 최근 상품 Side Bar
- [x] Footer (배민 문방구 가져다 쓰기)
- [x] Product에 하트, 카트 고정

**Comment by peanut-lover** [comment]
실제 소요시간: 2MD (라우터 수정 및 테스트 케이스 작성에 시간이 꽤 많이 쓰였습니다.)
